name: GitHub Metrics

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_PAT }}

          user: RusdiEneri
          template: classic
          base: header, activity, community, repositories, metadata

          config_timezone: Asia/Jakarta

          # contribution graph
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # coding habits
          plugin_habits: yes
          plugin_habits_days: 30

          # repo traffic
          plugin_traffic: yes

          # language usage
          plugin_languages: yes
          plugin_languages_limit: 8

          # stars
          plugin_stars: yes

          # achievements
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C

          # streak
          plugin_streak: yes
          plugin_streak_days: 30

          # repo stats
          plugin_repositories: yes
          plugin_repositories_featured: 6
          plugin_repositories_order: pushed

          # tech stack
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: mastered

          # code volume
          plugin_lines: yes

          # skyline visual
          plugin_skyline: yes
          plugin_skyline_year: current-year

          # activity detail
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14

          plugin_wakatime: yes
          plugin_wakatime_days: 7
