name: GitHub Metrics

on:
  schedule:
    - cron: "0 */6 * * *" # update tiap 6 jam (lebih ringan)
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_PAT }}

          user: RusdiEneri
          template: classic
          base: header, activity, community, repositories, metadata

          config_timezone: Asia/Jakarta

          # contribution graph
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # coding habits
          plugin_habits: yes
          plugin_habits_days: 30

          # repo traffic
          plugin_traffic: yes

          # language usage
          plugin_languages: yes
          plugin_languages_limit: 8

          # stars & followers
          plugin_stars: yes
          plugin_followup: yes
