name: GitHub Metrics

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # GENERAL STATS
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_PAT }}
          filename: metrics.general.svg
          committer_message: "chore: update general metrics"

          user: RusdiEneri
          template: terminal
          base: header, activity, community, repositories

          config_timezone: Asia/Jakarta
          config_display: large
          config_padding: 0, 0

      # LANGUAGES
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_PAT }}
          filename: metrics.languages.svg
          committer_message: "chore: update languages metrics"

          user: RusdiEneri
          template: terminal
          base: ""

          config_timezone: Asia/Jakarta
          config_display: large
          config_padding: 0, 0

          plugin_languages: yes
          plugin_languages_limit: 8

      # ACHIEVEMENTS
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_PAT }}
          filename: metrics.achievements.svg
          committer_message: "chore: update achievements metrics"

          user: RusdiEneri
          template: terminal
          base: ""

          config_timezone: Asia/Jakarta
          config_display: large
          config_padding: 0, 0

          plugin_achievements: yes
          plugin_achievements_display: detailed
