name: GitHub Metrics

on:
  schedule:
    - cron: "0 */6 * * *" # update tiap 6 jam (lebih ringan)
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_PAT }}

          user: RusdiEneri
          template: classic
          base: header, activity, community, repositories, metadata

          config_timezone: Asia/Jakarta

          # contribution graph
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # coding habits
          plugin_habits: yes
          plugin_habits_days: 30

          # repo traffic
          plugin_traffic: yes

          # language usage
          plugin_languages: yes
          plugin_languages_limit: 8

          # stars & followers
          plugin_stars: yes
          plugin_followup: yes

          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C

          plugin_streak: yes
          plugin_streak_days: 30

          plugin_repositories: yes
          plugin_repositories_featured: 6
          plugin_repositories_order: starred

          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: mastered

          plugin_lines: yes

          plugin_skyline: yes
          plugin_skyline_year: current-year

          plugin_wakatime: yes
          plugin_wakatime_days: 7

          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14

          template: terminal
